remote_theme: pages-themes/cayman@v0.2.0

title: Платформа створення електронних карток на батьківські збори

description: Розроблений програмний продукт являє собою веб-застосунок для створення електроних карток на батьківські збори за допомогою якого викладачі коледжу можуть генерувати картки на збори, налаштовувати їх фон та колір тексту. Слід подбати про можливість редагування карток, перетворення їх на PDF-документ і завантаження на власний компютер.
